### ISSUE TITLE
Trouble with proceeding .wfn files

### ISSUE THREAD

**Issue by mminzar** [juliacontrerasgarcia/nciplot#4]
Hello,

I am a PhD student and I've tried to use nciplot for my systems.
I have managed to solve test cases with nciplot, however, when I tried it for my own cases it didn't work.

It gave me the Error: "At line 187 of file reader.f90 (unit = 10, file = 'pti2codchi3.wfn')
Fortran runtime error: Bad value during floating point read
Error termination. Backtrace:
Could not print backtrace: libbacktrace could not find executable to open".

I assume the problem may be is in the .wfn file, however, my .wfn input file looks similar to the example one ( the only difference is I have "The total energy" in the last line of my .wfn file and test case has "The HF Energy", so I am very confused about what is wrong and how can I fix that issue.
I have generated my .wfn files in Gaussian ( with these input lines:

"%NProcShared=24
%Chk=i2.chk
%mem=30GB
#p PBE1PBE/gen EmpiricalDispersion=GD3 pseudo=read scfcyc=1000 pop=(full,NBO)
Output=WFN geom=check guess=check"

Can you please give me a hint of what shall I do to overcome this problem?
With the hope for your help,
Here are my input files for last calculation.
https://drive.google.com/file/d/1wypAL8zrcKETJCNoYJvGW_US0ecTb-IQ/view?usp=sharing

https://drive.google.com/file/d/1CNjbDWzHDW1uNPVkRaH1uV5isw-I1yy9/view?usp=sharing

https://drive.google.com/file/d/1c7s95HyljVxPPG3J3xYqB0AF1b_6zURF/view?usp=sharing

Margarita

**Comment by rlaplaza** [comment]
At a first glance, I imagine that the problem is with the pseudopotentials. Gaussian's wfn format does not really mix well with pseudopotentials.

I will try to have a look, but the current version should work with wfx files, meaning you just need to change the output=wfn to output=wfx line in your Gaussian input. The pseudos are better dealt with in that format.

Again, I will try and get back to you, we are trying to get the GitHub moving now that the code has been published. 

Thank you for the input and sorry for the delay!
