### ISSUE TITLE
COARSE FINE and ULTRAFINE keyword not recognise

### ISSUE THREAD

**Issue by vliegeois** [juliacontrerasgarcia/nciplot#6]
Hi

In the manual, you mention the keywords COARSE, FINE and ULTRAFINE but this keywords are not recognised and indeed does not appear in the nciplot.f90 code.

Best regards

Vincent

**Comment by rlaplaza** [comment]
Hello. This one has been a timing issue. The manual, which includes this keywords, belonged to a development version in which some issues have been fixed (mostly related with memory leaks).

The COARSE, FINE and ULTRAFINE Keywords have been added for quality of life and simplicity, just so that the user does not need to bother with INCREMENTS and CG2FG. Everything should work now! 

Again, thank you for your input!
